name: antara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  day_night_time_picker: any
  skeletons: any
  sqflite: any
  cupertino_icons: ^1.0.2
  convex_bottom_bar: ^3.2.0
  get: ^4.6.5
  intl: ^0.18.1
  date_picker_timeline: ^1.2.5
  flutter_secure_storage: 8.0.0
  material_design_icons_flutter: 7.0.7296
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/logo.png
    - assets/images/makan.png
    - assets/images/minum.png
    - assets/images/tidur.png
    - assets/images/olahraga.png
  fonts: 
    - family: poppins
      fonts: 
        - asset: assets/fonts/Poppins-Bold.ttf
  uses-material-design: true
weight: 800
